method: grid
metric:
  name: funkcja_straty
  goal: minimize
parameters:
  batch_size:
    values: [32, 64]
  optimizer:
    values: ["adam", "sgd"]
  fc_layer_size:
    value: 128
  dropout:
    value: 0.3
  learning_rate:
    value: 0.005
  epochs:
    value: 5
