method: grid
metric:
  name: loss
  goal: minimize
  summary: minimize
parameters:
  batch_size:
    values: [32]
  optimizer:
    values: ["adam", "sgd"]
  fc_layer_size:
    value: 128
  dropout:
    value: 0.3
  learning_rate:
    values: [0.001]
  epochs:
    value: 5
