method: bayes
metric:
  name: loss
  goal: minimize
parameters:
  batch_size:
    values: [32, 64, 128]
  fc_layer_size:
    values: [64, 128, 256]
  dropout:
    min: 0.2
    max: 0.5
  optimizer:
    values: ["adam", "sgd"]
  learning_rate:
    min: 0.001
    max: 0.01
  epochs:
    value: 5
