method: grid
metric:
  name: loss
  goal: minimize
parameters:
  batch_size:
    values: [32]
  fc_layer_size:
    values: [64, 128, 256]
  dropout:
    values: [0.1]
  optimizer:
    values: ["adam", "sgd"]
  learning_rate:
    values: [0.001]
  epochs:
    value: 5
